### ISSUE TITLE
Page/widget for local agencies and emergency contacts

### ISSUE THREAD

**Issue by Spasmaticus** [imprex92/dark-traveling-marshmallow#96] opened 2023-06-09 18:53 UTC
This is a suggestion for displaying information related to what help you as a traveler can get at a certain location, the page could be accessible on the main page.

A page displaying contact details and links to local agencies that can help travelers. Data should be fetched automatically if possible.
Should not be a widget as this is used less frequently. Needs to be easy to use with good visibility in case of emergency.

To include:
Paramedics
Police
Embassy
and perhaps ICE (in case of emergency), but this the user has to add themselves. Could be relatives etc. Consider GDPR.

Should contain a free text field with personal notes that the traveler can add in case they find more useful contacts locally that they want to add, for example "Great taxi service +1 123456 789". Info here needs to be saved.

**Comment by imprex92** [comment] 2024-03-20 14:35
Duplicate of #98

**Closed by imprex92** 2024-03-20 14:35 UTC
Labels: enhancement
